export const INTEGRATIONS_CONFIG = {
  hubspot: {
    id: 'hubspot',
    title: 'HubSpot CRM',
    icon: '🔴',
    description: 'Sincronize clientes e orçamentos com HubSpot',
    credentialLabel: 'API Key do HubSpot',
    credentialPlaceholder: 'Paste your HubSpot API key',
    credentialType: 'password',
    helpText: 'Encontre em Settings → Integrations & Apps → Private Apps',
    docLink: 'https://developers.hubspot.com/docs/api/private-apps',
    status: 'active',
  },
  sendgrid: {
    id: 'sendgrid',
    title: 'SendGrid',
    icon: '📧',
    description: 'Envie emails com SendGrid em vez de SMTP local',
    credentialLabel: 'API Key do SendGrid',
    credentialPlaceholder: 'Paste your SendGrid API key',
    credentialType: 'password',
    helpText: 'Encontre em Settings → API Keys',
    docLink: 'https://docs.sendgrid.com/for-developers/authentication',
    status: 'active',
  },
  slack: {
    id: 'slack',
    title: 'Slack',
    icon: '💬',
    description: 'Receba notificações de orçamentos no Slack',
    credentialLabel: 'Webhook URL do Slack',
    credentialPlaceholder: 'https://hooks.slack.com/services/...',
    credentialType: 'password',
    helpText: 'Crie em Apps → Incoming Webhooks',
    docLink: 'https://api.slack.com/messaging/webhooks',
    status: 'active',
  },
  docusign: {
    id: 'docusign',
    title: 'DocuSign',
    icon: '✍️',
    description: 'Envie documentos para assinatura digital',
    status: 'coming_soon',
  },
  google_drive: {
    id: 'google_drive',
    title: 'Google Drive',
    icon: '☁️',
    description: 'Faça backup automático de dados no Google Drive',
    status: 'coming_soon',
  },
};

export const SECURITY_TIPS = [
  'Mantenha suas API keys seguras e não as compartilhe',
  'Você pode regenerar chaves a qualquer momento no painel do serviço',
  'Nunca coloque credenciais em controle de versão',
  'Use variáveis de ambiente em produção',
];
